# apiVersion: networking.istio.io/v1alpha3
# kind: Gateway
# metadata:
#   name: solar-system-gateway
# spec:
#   servers:
#   - hosts:
#       - "*"
#   - port:
#       number: 80
#       name: http
#       protocol: HTTP

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: solar-system
  namespace: istio-ingress
spec:
  selector:
    #istio: ingressgateway
    #app: istio-ingressgateway
    app: istio-ingress
    istio: ingress
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: istio-ingress
  name: ingress
  namespace: solar-system
spec:
  rules:
  - host: istio.aspiresoftware.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: solar-system-service
            port:
              number: 80