apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: solar-vsvc
spec:
  hosts:
  - "istio.aspiresoftware.dev"
  gateways:
  - solar-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: solar-system-service 
        port:
          number: 80