# apiVersion: networking.istio.io/v1alpha3
# kind: VirtualService
# metadata:
#   name: solar-vsvc
# spec:
#   hosts:
#   - "*"
#   gateways:
#   - solar-gateway
#   http:
#   - route:
#     - destination:
#         host: solar-system-service 
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: solar-vsvc
spec:
  hosts:
  - "*"
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 80
        host: solar-system-service
